# Generated by Django 5.1.6 on 2025-03-05 05:52

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(default=10)),
                ('image_big', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=95, scale=None, size=[1440, 640], upload_to='banner/images', verbose_name='Баннер десктоп')),
                ('image_small', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, null=True, quality=95, scale=None, size=[760, 640], upload_to='banner/images', verbose_name='Баннер мобилка')),
                ('text_big', models.TextField(blank=True, null=True, verbose_name='Текст большой')),
                ('text_small', models.TextField(blank=True, null=True, verbose_name='Текст маленький')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
                'ordering': ['order_num'],
            },
        ),
        migrations.CreateModel(
            name='CallbackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Имя')),
                ('email', models.EmailField(max_length=255, null=True, verbose_name='email')),
                ('phone', models.CharField(max_length=255, null=True, verbose_name='Телефон')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тема')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('file', models.FileField(blank=True, null=True, upload_to='forms', verbose_name='Файл')),
                ('is_done', models.BooleanField(default=False, verbose_name='Обработана')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.IntegerField(default=10)),
                ('question', models.CharField(max_length=255, null=True, verbose_name='Вопрос')),
                ('answer', models.TextField(null=True, verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Faq',
                'verbose_name_plural': 'Faq',
                'ordering': ['order_num'],
            },
        ),
    ]
