# Generated by Django 5.1.6 on 2025-03-10 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
        ('shop', '0002_product_name_lower_alter_productunit_add_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callbackform',
            name='email',
        ),
        migrations.RemoveField(
            model_name='callbackform',
            name='file',
        ),
        migrations.RemoveField(
            model_name='callbackform',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='callbackform',
            name='text',
        ),
        migrations.AddField(
            model_name='callbackform',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='callbackform',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
