# Generated by Django 5.1.6 on 2025-03-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_callbackform_email_remove_callbackform_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callbackform',
            name='amount',
        ),
        migrations.AlterField(
            model_name='callbackform',
            name='product',
            field=models.CharField(max_length=255, null=True, verbose_name='Товар'),
        ),
    ]
