# Generated by Django 5.1.6 on 2025-03-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_remove_callbackform_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbackform',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='комметарий'),
        ),
        migrations.AlterField(
            model_name='callbackform',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='callbackform',
            name='product',
            field=models.CharField(max_length=255, null=True, verbose_name='Заказ'),
        ),
    ]
