# Generated by Django 5.1.6 on 2025-04-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_callbackform_comment_alter_callbackform_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='image_small',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image_big',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='text_big',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='text_small',
        ),
        migrations.AddField(
            model_name='banner',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
