# Generated by Django 5.1.6 on 2025-04-14 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_name_lower_alter_productunit_add_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Длина')),
            ],
            options={
                'verbose_name': 'Длина',
                'verbose_name_plural': 'Длина',
            },
        ),
        migrations.AddField(
            model_name='productunit',
            name='class_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.unitclass', verbose_name='Класс'),
        ),
    ]
