# Generated by Django 5.1 on 2024-08-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_image_productimage_is_main'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('order_num',), 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.RenameField(
            model_name='service',
            old_name='description',
            new_name='html_content',
        ),
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Короткое описание'),
        ),
    ]
