# Generated by Django 5.1.6 on 2025-04-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_unitclass_productunit_class_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitclass',
            options={'verbose_name': 'Класс', 'verbose_name_plural': 'Класс'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярный'),
        ),
        migrations.AlterField(
            model_name='unitclass',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Класс'),
        ),
    ]
