# Generated by Django 5.1 on 2024-08-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_productunit_options_product_display_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
