# Generated by Django 5.1 on 2024-08-14 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер заказа')),
                ('customer', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='контактный телефон')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='почта')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий к заказу')),
                ('payment_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='тип оплаты')),
                ('delivery_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='тип доставки')),
                ('delivery_address', models.TextField(blank=True, null=True, verbose_name='адрес доставки')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(blank=True, max_length=255, null=True, verbose_name='Артикул')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('unit', models.CharField(max_length=255, null=True, verbose_name='Ед. измерения')),
                ('price', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена')),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
            ],
        ),
    ]
